### ISSUE TITLE
Apropos on load-file -> ArithmeticException

### ISSUE THREAD

**Issue by lgrapenthin** [bhauman/rebel-readline#119]
Type "load-file" into REPL, hit C-x C-a
#error {
 :cause "Divide by zero"
 :via
 [{:type java.lang.ArithmeticException
   :message "Divide by zero"
   :at [clojure.lang.Numbers divide "Numbers.java" 163]}]
 :trace
 [[clojure.lang.Numbers divide "Numbers.java" 163]
  [clojure.lang.Numbers divide "Numbers.java" 3813]
  [rebel_readline.clojure.widgets$standard_deviation invokeStatic "widgets.clj" 285]
  [rebel_readline.clojure.widgets$standard_deviation invoke "widgets.clj" 279]
  [rebel_readline.clojure.widgets$two_standards_plus_mean invokeStatic "widgets.clj" 291]
  [rebel_readline.clojure.widgets$two_standards_plus_mean invoke "widgets.clj" 290]
  [rebel_readline.clojure.widgets$eliminate_long_outliers invokeStatic "widgets.clj" 297]
  [rebel_readline.clojure.widgets$eliminate_long_outliers invoke "widgets.clj" 296]
  [rebel_readline.clojure.widgets$divide_into_displayable_columns invokeStatic "widgets.clj" 313]
  [rebel_readline.clojure.widgets$divide_into_displayable_columns invoke "widgets.clj" 311]
  [rebel_readline.clojure.widgets$formatted_apropos invokeStatic "widgets.clj" 330]
  [rebel_readline.clojure.widgets$formatted_apropos invoke "widgets.clj" 325]
  [rebel_readline.clojure.widgets$apropos_at_point_widget$reify__4593 apply "widgets.clj" 341]
  [org.jline.reader.impl.LineReaderImpl readLine "LineReaderImpl.java" 552]
  [org.jline.reader.impl.LineReaderImpl readLine "LineReaderImpl.java" 390]
  [sun.reflect.NativeMethodAccessorImpl invoke0 "NativeMethodAccessorImpl.java" -2]
  [sun.reflect.NativeMethodAccessorImpl invoke "NativeMethodAccessorImpl.java" 62]
  [sun.reflect.DelegatingMethodAccessorImpl invoke "DelegatingMethodAccessorImpl.java" 43]
  [java.lang.reflect.Method invoke "Method.java" 498]
  [clojure.lang.Reflector invokeMatchingMethod "Reflector.java" 93]
  [clojure.lang.Reflector invokeInstanceMethod "Reflector.java" 28]
  [rebel_readline.core$read_line invokeStatic "core.clj" 121]
  [rebel_readline.core$read_line doInvoke "core.clj" 78]
  [clojure.lang.RestFn invoke "RestFn.java" 423]
  [rebel_readline.core$repl_read_line invokeStatic "core.clj" 141]
  [rebel_readline.core$repl_read_line invoke "core.clj" 129]
  [rebel_readline.core$create_buffered_repl_reader_fn$fn__4813$fn__4814 invoke "core.clj" 162]
  [clojure.main$repl$read_eval_print__8572$fn__8573 invoke "main.clj" 241]
  [clojure.main$repl$read_eval_print__8572 invoke "main.clj" 241]
  [clojure.main$repl$fn__8581 invoke "main.clj" 261]
  [clojure.main$repl invokeStatic "main.clj" 261]
  [clojure.main$repl doInvoke "main.clj" 177]
  [clojure.lang.RestFn invoke "RestFn.java" 512]
  [rebel_readline.main$_main invokeStatic "main.clj" 15]
  [rebel_readline.main$_main doInvoke "main.clj" 10]
  [clojure.lang.RestFn invoke "RestFn.java" 397]
  [clojure.lang.AFn applyToHelper "AFn.java" 152]
  [clojure.lang.RestFn applyTo "RestFn.java" 132]
  [clojure.lang.Var applyTo "Var.java" 702]
  [clojure.core$apply invokeStatic "core.clj" 657]
  [clojure.main$main_opt invokeStatic "main.clj" 317]
  [clojure.main$main_opt invoke "main.clj" 313]
  [clojure.main$main invokeStatic "main.clj" 424]
  [clojure.main$main doInvoke "main.clj" 387]
  [clojure.lang.RestFn applyTo "RestFn.java" 137]
  [clojure.lang.Var applyTo "Var.java" 702]
  [clojure.main main "main.java" 37]]}

**Comment by bhauman** [comment]
Thanks! However this has been fixed try 0.1.1-SNAPSHOT
