### ISSUE TITLE
Apropos on load-file -> IllegalArgumentException

### ISSUE THREAD

**Issue by lgrapenthin** [bhauman/rebel-readline#120]
Type "load-file", C-x C-a
#error {
 :cause "Don't know how to create ISeq from: clojure.core$map$fn__5583"
 :via
 [{:type java.lang.IllegalArgumentException
   :message "Don't know how to create ISeq from: clojure.core$map$fn__5583"
   :at [clojure.lang.RT seqFrom "RT.java" 550]}]
 :trace
 [[clojure.lang.RT seqFrom "RT.java" 550]
  [clojure.lang.RT seq "RT.java" 530]
  [clojure.core$seq__5124 invokeStatic "core.clj" 137]
  [clojure.core$map$fn__5587 invoke "core.clj" 2738]
  [clojure.lang.LazySeq sval "LazySeq.java" 40]
  [clojure.lang.LazySeq seq "LazySeq.java" 49]
  [clojure.lang.RT seq "RT.java" 528]
  [clojure.core$seq__5124 invokeStatic "core.clj" 137]
  [clojure.core$map$fn__5587 invoke "core.clj" 2738]
  [clojure.lang.LazySeq sval "LazySeq.java" 40]
  [clojure.lang.LazySeq seq "LazySeq.java" 49]
  [clojure.lang.RT seq "RT.java" 528]
  [clojure.core$seq__5124 invokeStatic "core.clj" 137]
  [clojure.core$interleave$fn__5950 invoke "core.clj" 4282]
  [clojure.lang.LazySeq sval "LazySeq.java" 40]
  [clojure.lang.LazySeq seq "LazySeq.java" 49]
  [clojure.lang.RT seq "RT.java" 528]
  [clojure.core$seq__5124 invokeStatic "core.clj" 137]
  [clojure.core$drop$step__5646 invoke "core.clj" 2919]
  [clojure.core$drop$fn__5649 invoke "core.clj" 2924]
  [clojure.lang.LazySeq sval "LazySeq.java" 40]
  [clojure.lang.LazySeq seq "LazySeq.java" 49]
  [clojure.lang.RT seq "RT.java" 528]
  [clojure.core$seq__5124 invokeStatic "core.clj" 137]
  [clojure.core$apply invokeStatic "core.clj" 652]
  [clojure.core$apply invoke "core.clj" 652]
  [rebel_readline.clojure.line_reader$formatted_apropos invokeStatic "line_reader.clj" 671]
  [rebel_readline.clojure.line_reader$formatted_apropos invoke "line_reader.clj" 660]
  [rebel_readline.clojure.line_reader$apropos_at_point_widget$reify__4610 apply "line_reader.clj" 676]
  [org.jline.reader.impl.LineReaderImpl readLine "LineReaderImpl.java" 552]
  [rebel_readline.jline_api.proxy$org.jline.reader.impl.LineReaderImpl$IAtom$IDeref$4ac0129f readLine nil -1]
  [org.jline.reader.impl.LineReaderImpl readLine "LineReaderImpl.java" 390]
  [rebel_readline.jline_api.proxy$org.jline.reader.impl.LineReaderImpl$IAtom$IDeref$4ac0129f readLine nil -1]
  [sun.reflect.NativeMethodAccessorImpl invoke0 "NativeMethodAccessorImpl.java" -2]
  [sun.reflect.NativeMethodAccessorImpl invoke "NativeMethodAccessorImpl.java" 62]
  [sun.reflect.DelegatingMethodAccessorImpl invoke "DelegatingMethodAccessorImpl.java" 43]
  [java.lang.reflect.Method invoke "Method.java" 498]
  [clojure.lang.Reflector invokeMatchingMethod "Reflector.java" 93]
  [clojure.lang.Reflector invokeInstanceMethod "Reflector.java" 28]
  [rebel_readline.core$read_line invokeStatic "core.clj" 102]
  [rebel_readline.core$read_line doInvoke "core.clj" 62]
  [clojure.lang.RestFn invoke "RestFn.java" 408]
  [rebel_readline.core$repl_read_line invokeStatic "core.clj" 122]
  [rebel_readline.core$repl_read_line invoke "core.clj" 110]
  [rebel_readline.core$create_buffered_repl_reader_fn$fn__677$fn__678 invoke "core.clj" 143]
  [clojure.main$repl$read_eval_print__8572$fn__8573 invoke "main.clj" 241]
  [clojure.main$repl$read_eval_print__8572 invoke "main.clj" 241]
  [clojure.main$repl$fn__8581 invoke "main.clj" 261]
  [clojure.main$repl invokeStatic "main.clj" 261]
  [clojure.main$repl doInvoke "main.clj" 177]
  [clojure.lang.RestFn applyTo "RestFn.java" 137]
  [clojure.core$apply invokeStatic "core.clj" 657]
  [clojure.core$apply invoke "core.clj" 652]
  [rebel_readline.clojure.main$repl_STAR_ invokeStatic "main.clj" 69]
  [rebel_readline.clojure.main$repl_STAR_ invoke "main.clj" 61]
  [rebel_readline.clojure.main$repl invokeStatic "main.clj" 78]
  [rebel_readline.clojure.main$repl doInvoke "main.clj" 77]
  [clojure.lang.RestFn invoke "RestFn.java" 397]
  [rebel_readline.clojure.main$_main invokeStatic "main.clj" 99]
  [rebel_readline.clojure.main$_main doInvoke "main.clj" 98]
  [clojure.lang.RestFn invoke "RestFn.java" 397]
  [clojure.lang.AFn applyToHelper "AFn.java" 152]
  [clojure.lang.RestFn applyTo "RestFn.java" 132]
  [clojure.core$apply invokeStatic "core.clj" 657]
  [clojure.core$apply invoke "core.clj" 652]
  [rebel_readline.main$_main invokeStatic "main.clj" 6]
  [rebel_readline.main$_main doInvoke "main.clj" 5]
  [clojure.lang.RestFn invoke "RestFn.java" 397]
  [clojure.lang.AFn applyToHelper "AFn.java" 152]
  [clojure.lang.RestFn applyTo "RestFn.java" 132]
  [clojure.lang.Var applyTo "Var.java" 702]
  [clojure.core$apply invokeStatic "core.clj" 657]
  [clojure.main$main_opt invokeStatic "main.clj" 317]
  [clojure.main$main_opt invoke "main.clj" 313]
  [clojure.main$main invokeStatic "main.clj" 424]
  [clojure.main$main doInvoke "main.clj" 387]
  [clojure.lang.RestFn applyTo "RestFn.java" 137]
  [clojure.lang.Var applyTo "Var.java" 702]
  [clojure.main main "main.java" 37]]}

**Comment by bhauman** [comment]
Thanks!!
