### ISSUE TITLE
suggestion: alternative bindings for Clojure widgets in vi mode

### ISSUE THREAD

**Issue by schmee** [bhauman/rebel-readline#127]
The bindings for the Clojure-specific widgets feel somewhat out of place in vi mode. In Vim the leader key, which defaults to `\`, is often used to prefix user-specific commands. My suggestion is to replace the current bindings for the Clojure widgets in vi mode with leader keybinds, e.g:

- Eval: `Ctrl+X,Ctrl+E` => `\e`
- Doc: `Ctrl+X,Ctrl+D` => `\d`
- Apropos: `Ctrl+X,Ctrl+A` => `\a`

and so on. What do you think?

**Comment by bhauman** [comment]
I'm afraid I don't know what "leader-based equivalents" means :)

**Comment by schmee** [comment]
Sorry for the confusing wording, I simply meant "keybindings that start with the leader key (`\`). I've updated the wording in the original issue.

**Comment by bhauman** [comment]
Is this for both :viins and :vicmd modes?

**Comment by schmee** [comment]
This would be for `vicmd` only, the canonical thing in Vim (at least IMO) is to switch to normal mode when you want to do anything that is not inserting text. As far as I'm concerned these things don't need to have any bindings at all in insert mode.

**Comment by bhauman** [comment]
I'm of the mind to leave it in :viins as there is no cost, and it offers a significant convenience to users.

**Comment by bhauman** [comment]
The bindings do make sense to me. I think I'll make them in addition to the original bindings, as there is a simplicity, to having the same bindings for these query features everywhere.
