### ISSUE TITLE
trouble running rebel-readline globally with Leiningen

### ISSUE THREAD

**Issue by indraniel** [bhauman/rebel-readline#134]
I was following the README and trying to run `rebel-readline` globally and encountered this error when trying to invoke the REPL:

```bash
$ cd
$ lein trampoline run -m rebel-readline.main
Couldn't find project.clj, which is needed for trampoline
```

Before I ran the above commands, I updated my `~/.lein/profiles.clj` as so:

```clojure
{:user {:plugins      [[lein-try "0.4.3"]
                       [cider/cider-nrepl "0.16.0"]]
        :dependencies [[com.bhauman/rebel-readline "0.1.1"]]}}
```

However, when I attempt to run the REPL within a project, everything seems to work as expected.  In particular, when I do the following:

```bash
$ lein new foo
$ cd foo/
```

and edit the `project.clj` file to include `[com.bhauman/rebel-readline "0.1.1"]` as a dependency,  then, while in the `foo` project directory, everything seems to work fine:

```bash
$ lein trampoline run -m rebel-readline.main
[Rebel readline] Type :repl/help for online help info
user=>
```

Am I doing something amiss, or simply misunderstanding the README?

**Comment by bhauman** [comment]
Yes you are more missunderstanding the Readme.  You need to be in a project directory.
