### ISSUE TITLE
Cant invoke source 

### ISSUE THREAD

**Issue by metacritical** [bhauman/rebel-readline#136]
For some reason, after invoking the quick start command :

> `clojure -Sdeps "{:deps {com.bhauman/rebel-readline {:mvn/version \"0.1.1\"}}}" -m rebel-readline.main`

 I cant execute `(source max)` it throws an error 

> `CompilerException java.lang.RuntimeException: Unable to resolve symbol: source in this context, compiling:(NO_SOURCE_PATH:1:1) 
`

**Comment by bhauman** [comment]
This is because I didn't include the repl helpers that clojure main does by
default. This is easy enough to do.

**Comment by bhauman** [comment]
You do realize that you can hit ctrl-X ctrl-S to get the source code in
rebel-readline?

**Comment by metacritical** [comment]
No i didnt know that, but thanks!

**Comment by metacritical** [comment]
How can i include the repl helpers on my own?

**Comment by bhauman** [comment]
(require '[clojure.repl :refer :all])

**Comment by metacritical** [comment]
Thankyou

**Comment by borkdude** [comment]
With clojure, you can create an alias like this:

``` clojure
           :rebel {:extra-deps {org.clojure/clojure {:mvn/version "1.12.0-alpha2"}
                                com.bhauman/rebel-readline {:mvn/version "0.1.4"}}
                   :main-opts  ["-e" "(apply require clojure.main/repl-requires)"
                                "-m" "rebel-readline.main"]}
```

and then invoke `clojure -M:rebel` to get `source`, etc in your REPL. With clojure 1.12 you'll also get `add-lib` which lets you add libraries in your REPL without restarting it.
