### ISSUE TITLE
Can't rebind CTRL-U to backward-kill-line

### ISSUE THREAD

**Issue by lxsli** [bhauman/rebel-readline#146]
I checked the JLine3 source: https://github.com/jline/jline3/blob/29a10451d0149c5e5c2e323a41788b99a2a4db60/reader/src/main/java/org/jline/reader/LineReader.java

and spotted a backward-kill-line widget. I wrote ~/.clojure/rebel_readline.edn:

    {:key-map :viins
     :key-bindings {:viins [["^U" :backward-kill-line]]}}

but it doesn't work :(

Also (and I can open a separate issue for this if you want) it takes a long time to start the REPL so experimenting is annoying. A `:repl/set-keybind "^U" backward-kill-line` command would be very convenient.

**Comment by bhauman** [comment]
I think you are not using the latest version "0.1.2" of rebel-readline as this works fine for me.

**Comment by lxsli** [comment]
Ah yep, thanks
