### ISSUE TITLE
Binding to forcefully send the command to the REPL

### ISSUE THREAD

**Issue by alexander-yakushev** [bhauman/rebel-readline#153]
It gets quite tiresome when I edit something inside the form, and then when I press <kbd>Return</kbd> the form isn't sent to the REPL but a newline is inserted at point. What is more annoying is that I then have to <kbd>Backspace</kbd> the [now reindented] line all the way back to the previous line, then <kbd>Down</kbd> all the way down, <kbd>C-e</kbd> and finally <kbd>Return</kbd>.

It would be nice if something like <kbd>Ctrl-Return</kbd> were available to send the form in regardless of the cursor position.

**Comment by bhauman** [comment]
This has been addressed already #101 #152
