### ISSUE TITLE
StackOverflowError when output a big string

### ISSUE THREAD

**Issue by razum2um** [bhauman/rebel-readline#161]
example steps to reproduce:
```sh
clojure -Sdeps "{:deps {com.bhauman/rebel-readline {:mvn/version \"0.1.3\"}}}" -m rebel-readline.main
```
```clojure
user=> (->> (iterate inc 0) (take 10000) (clojure.string/join "\n"))
StackOverflowError   java.util.regex.Pattern$GroupTail.match (Pattern.java:4836)
```
The max length may vary. I hit this when reading a big line from file.

`clojure.main` prints line ok, so it's regexp-based (highlighting?)  to blame (e.g. https://stackoverflow.com/questions/7509905/java-lang-stackoverflowerror-while-using-a-regex-to-parse-big-strings)

**Comment by bhauman** [comment]
Yeah should be able to fix this by detecting string size before highlighting

**Comment by bhauman** [comment]
Actually this is not really a fix, but it falls back to regular printing when it hits the overflow condition.
