### ISSUE TITLE
how to start rebel-readline with Clojure tools?

### ISSUE THREAD

**Issue by johbra** [bhauman/rebel-readline#168]
If I try to start rebel-readline as described :
clojure -Sdeps "{:deps {com.bhauman/rebel-readline {:mvn/version \"0.1.4\"}}}" -m rebel-readline.main
I get:
java.lang.ClassNotFoundException: clojure.main

If I use clj instead of clojure:
clj -Sdeps "{:deps {com.bhauman/rebel-readline {:mvn/version \"0.1.4\"}}}" -m rebel-readline.main
[Rebel readline] Type :repl/help for online help info
user=> 
All seems to work fine.

**Comment by johbra** [comment]
Now, I've found the source of the problem. I'd got an "old" alias named clojure in my .profile. Now all works fine.

Johannes

**Comment by bhauman** [comment]
coolio, closing this out :)
