### ISSUE TITLE
Auto Reload

### ISSUE THREAD

**Issue by viebel** [bhauman/rebel-readline#169]
`rebel-readline` is awesome.
Is there a way to auto reload a namespace every time a source file changes (without having to re-require the namespace)?

**Comment by bhauman** [comment]
You can create a function to do this for you in your `user.clj` file.

Use hawk to watch the directory that you want:
https://github.com/wkf/hawk/tree/master/src/main/clojure/hawk 

Extra Credit: handle load time exceptions and format the errors nicely and print them out.

Extra Extra Credit: make a library out of it

**Comment by viebel** [comment]
Thanks for the tip @bhauman.

I ended up writing this piece of code in my `user.clj`:

~~~clojure
(hawk/watch! [{:paths ["src/calculator"]
               :handler (fn [ctx e]
                          (future
                            (repl/refresh)))}])
~~~

Would it make sense to try having a `user.clj` that is common to all my clojure projects or should I simply replicate it to each one of my clojure projects?
