### ISSUE TITLE
Add deps.edn to allow use of master with clojure

### ISSUE THREAD

**Issue by seancorfield** [bhauman/rebel-readline#176]
Currently, `clojure` has to specify `rebel-readline` as a `:mvn/version` dependency and can only pull in released versions. It would be great if you provided `deps.edn` so `clojure` users could specify the dependency as a `:git/url` and `:sha` to pull down and test unreleased versions.

**Comment by bhauman** [comment]
Added a deps.edn file, it works locally just fine. Please give it a try and see if it's working correctly for you.

**Comment by bhauman** [comment]
This I could put one at the top that had the right source-paths and included both readline and cljs libraries in the short term

**Comment by seancorfield** [comment]
Confirmed, yes, a bug in `tools.deps` is preventing this from working properly: local deps don't work properly inside a git dependency.

Thanks for trying. https://github.com/seancorfield/rebel-readline/blob/master/deps.edn was my attempt at getting this to work (but blocked by the bug in `tools.deps`).
