### ISSUE TITLE
undisplay the `#_=>` signs

### ISSUE THREAD

**Issue by viebel** [bhauman/rebel-readline#181]
Is there a way in rebel-readline not to display the `#_=>` signs? (edited)
```
user=> (defn greater-than-42? [x]
  #_=>    (> x 42))
```

The reason I need this feature is that to allow me to copy past code snippets from the REPL into a blog post and to allow readers to copy/paste the code snippets back to their REPL

Currently if you copy paste the code after the `user=>` string into the REPL, you get a double `#_=>` sign
```
(defn greater-than-42? [x]
  #_=>   #_=>    (> x 42))
```
I am not sure that I have been 100% clear
Let me know if you want me to clarify it a bit more

**Comment by viebel** [comment]
@bhauman any idea about this issue?

**Comment by bhauman** [comment]
Yeah this falls way way down my list of priorities unfortunately.  You are welcome to have a look at the code and make a configuration option to disable this.  I don't know why you are getting two cursors on paste.
