### ISSUE TITLE
Make history project local

### ISSUE THREAD

**Issue by bhauman** [bhauman/rebel-readline#39]
I think there is a configuration somewhere in Jline to have history logged to a file, find it and turn it on and/or give it a config parameter in service.core

**Comment by christoph-frick** [comment]
With `rlwrap` i usually use a "project local" history.  So it would be great to have it configurable.  But since passing params around might not be an option, also honouring environment or system properties would be nice.

**Comment by bhauman** [comment]
I think you are correct that it should be a project local history.
