### ISSUE TITLE
Allow passing of initial `key-map` via config

### ISSUE THREAD

**Issue by christoph-frick** [bhauman/rebel-readline#85]
I don't know, if jline reads something like `.inputrc` (seems not to have an effect) and it's just disabled right now or if there are other means to got straight to e.g. `:viins`.  It would be great in any case to have that part of the config map to allow a preset.

**Comment by trptcolin** [comment]
[JLine3 removed inputrc support](https://github.com/jline/jline3/issues/230). There are probably other ways to get this same value (config on startup)... or folks may be able to re-institute inputrc support in jline3?

**Comment by christoph-frick** [comment]
Config would be great for my usecase.  I tried `:init` with the REPL, but that does not go through the rebel-rl channels.

**Comment by bhauman** [comment]
When you create a line-reader you have to give it a service.
You can pass the Service an initial config right now, but the key-map isn't one of the options yet.

This would be a first step towards allowing configuration of the key-map.

**Comment by christoph-frick** [comment]
@bhauman would you accept a PR for that? I could give it a shot: starting from the default config with `:key-map :emacs` trying to do `set-key-map!` call at the right place/time?

**Comment by bhauman** [comment]
I'm going to give it a shot real quick here because I want to do some thinking about this. We're going to need to have a way to respect the the initial config when it requires state changes to the jline-reader. So I'm probably going to create something like `service.core/init` function where all these things can be handled.

**Comment by christoph-frick** [comment]
Works like a charm.  Thank you very much!

**Comment by bhauman** [comment]
@christoph-frick this will work even better for you
